{{/*
SPDX-License-Identifier: PMPL-1.0-or-later
*/}}
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hypatia.secretsName" . }}
  namespace: {{ include "hypatia.namespace" . }}
  labels:
    {{- include "hypatia.labels" . | nindent 4 }}
type: Opaque
data:
  arangodb-user: {{ .Values.secrets.arangodb.user | b64enc | quote }}
  arangodb-password: {{ .Values.secrets.arangodb.password | b64enc | quote }}
  arangodb-root-password: {{ .Values.secrets.arangodb.password | b64enc | quote }}
  dragonfly-password: {{ .Values.secrets.dragonfly.password | b64enc | quote }}
  {{- if .Values.secrets.github.token }}
  github-token: {{ .Values.secrets.github.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.gitlab.token }}
  gitlab-token: {{ .Values.secrets.gitlab.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bitbucket.user }}
  bitbucket-user: {{ .Values.secrets.bitbucket.user | b64enc | quote }}
  bitbucket-app-password: {{ .Values.secrets.bitbucket.appPassword | b64enc | quote }}
  {{- end }}
{{- end }}
